GET http://localhost:8080/app/ 

###
GET http://localhost:8080/app/assets/logo.png

###
GET http://localhost:8080/api/healthz

###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
   "body": "Hello, world!",
   "user_id": "123e4567-e89b-12d3-a456-426614174000"
}

###
GET http://localhost:8080/api/chirps

###
GET http://localhost:8080/api/chirps/355d52be-91f2-492b-8ed5-d4ec79d71593

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
   "password": "04234",
   "email": "lane@example.com"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
   "password": "04234",
   "email": "lane@example.com"
}

###
GET http://localhost:8080/admin/metrics

###
POST http://localhost:8080/admin/reset

